stages:
  - release

goreleaser:
  stage: release
  image:
    name: registry.trendyol.com/platform/base/image/gythialy/golang-cross:v1.16.6@sha256:a31f3981571aab561bfdc2c50bf25142f2460a47c35e76ae9d50826e3a1aabac
    entrypoint: [""]
  script:
    - make release
  only:
    refs:
      - tags