stages:
  - release

goreleaser:
  stage: release
  image: registry.trendyol.com/platform/base/image/docker:19.03.5
  variables:
    DOCKER_API_VERSION: "1.35"
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - alias: docker
      name: registry.trendyol.com/platform/base/image/docker:19.03.5-dind
  script:
    - |
      docker container run --rm --privileged \
      -v $(pwd):/kink \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -w /kink \
      --entrypoint="/bin/sh" \
      -e GITLAB_TOKEN=$GITLAB_TOKEN \
      -e DOCKER_REGISTRY=$DOCKER_REGISTRY \
      -e DOCKER_USERNAME=$DOCKER_USERNAME \
      -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
      registry.trendyol.com/platform/base/image/gythialy/golang-cross:v1.17 \
      -c "echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin && make release"
  only:
    refs:
      - tags
