language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

script:
  - composer install -n
  - vendor/bin/phpunit
  - rm -rf vendor
  - composer update --prefer-lowest -n
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then bash <(curl -s https://codecov.io/bash); fi
