[tool.poetry]
name = "django-saml2-auth"
version = "0.1.0"
description = "Django SAML2 Authentication Made Easy."
authors = ["Mostafa Moradian <mostafa@grafana.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pysaml2 = "7.4.2"
PyJWT = "2.8.0"
dictor = "0.1.11"
setuptools = "67.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.0"
pytest-django = "4.5.2"
responses = "0.23.3"
mypy = "1.4.1"
flake8 = "5.0.4"
django-stubs = "4.2.0"
types-pysaml2 = "1.0.1"
types-setuptools = "68.0.0.3"
types-pkg-resources = "0.1.3"
interrogate = "1.5.0"
coverage = "7.2.7"
cyclonedx-bom = "3.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
