version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1.0
  slack: circleci/slack@4

commands:
  slack_fail_notify:
    description: Notify Slack on failure
    steps:
      - slack/notify:
          event: fail
          channel: snyk-on-snyk-devex_ide
          branch_pattern: "main"
          template: basic_fail_1

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: ubuntu-latest
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          open-source-additional-arguments: --exclude=test

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: dx-local-alerts
      - security-scans:
          context: devex_ide
