version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1
  slack: circleci/slack@4

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: ubuntu-latest
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          open-source-additional-arguments: --exclude=test

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: 
          
      - security-scans:
          context: devex_ide
