version: '3.8'
services:
  postgres:
    image: 'postgres:15.2-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mercury_test
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -U postgres -d mercury_test"
      interval: 2s
      timeout: 5s
      retries: 5
