stages:
  - Prepare
  - Deploy

variables:
  FUNCTIONS: ''

Prepare:
  stage: Prepare
  script:
    - FUNCTIONS='['$(ls functions/*.json | xargs -n 1 basename | sed 's/\.json$//' | awk '{printf "\"%s\",", $0}' | sed 's/,$//')']'
    - |
      cat << EOF > template.gitlab-ci.yml
      stages:
        - Deploy

      Deploy:
        image:
          name: ghcr.io/trendyol/cbef:1.0.1-amd64
        stage: Deploy
        when: manual
        parallel:
          matrix:
            - FUNCTION: ${FUNCTIONS}
        script:
          - ln -s /cbef \${CI_PROJECT_DIR}/cbef
          - export CONFIG_FILE=./functions/\${FUNCTION}.json
          - ./cbef

      EOF

  artifacts:
    paths:
      - template.gitlab-ci.yml

Ready:
  stage: Prepare
  trigger:
    include:
      - artifact: template.gitlab-ci.yml
        job: Prepare
    forward:
      pipeline_variables: true
  needs:
    - job: Prepare
