stages:
  - Prepare
  - Deploy

variables:
  PROJECTS: ''

Prepare:
  stage: Prepare
  script:
    - PROJECTS='['$(ls functions/*.json | xargs -n 1 basename | sed 's/\.json$//' | awk '{printf "\"%s\",", $0}' | sed 's/,$//')']'
    - |
      cat << EOF > template.gitlab-ci.yml
      stages:
        - Deploy

      Deploy:
        image:
          name: ghcr.io/trendyol/cbef:latest-amd64
        stage: Deploy
        when: manual
        parallel:
          matrix:
            - PROJECT: ${PROJECTS}
        script:
          - ln -s /cbef \${CI_PROJECT_DIR}/cbef
          - export CONFIG_FILE=./functions/\${PROJECT}.json
          - export FUNCTION_FILE=./functions/\${PROJECT}.js
          - export EXECUTION_TIMEOUT=3m
          - ./cbef
      EOF

  artifacts:
    paths:
      - template.gitlab-ci.yml

Ready:
  stage: Prepare
  trigger:
    include:
      - artifact: template.gitlab-ci.yml
        job: Prepare
    forward:
      pipeline_variables: true
  needs:
    - job: Prepare
