FROM alpine:3.20@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d AS otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:8f9b68ea9c2d88710c1b904420ece52d391765d04e7a1732adb280d0afe96377

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
