name: Dependabot
# Fix yarn v2 cache files from dependabot PRs
# source: https://github.com/dependabot/dependabot-core/issues/1297#issuecomment-671131912

on:
  - pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.head.ref, 'dependabot/npm_and_yarn/')

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # minimize exposure
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Autofix lockfile
      env:
        YARN_ENABLE_SCRIPTS: 0 # disable postinstall scripts
      run: |
        yarn install
        yarn dedupe
    - name: Config Git
      run: |
        # use personal access token to allow triggering new workflow
        BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.DEPENDABOT_GITHUB_TOKEN }}" | base64)
        echo "::add-mask::$BASIC_AUTH"
        git config --global user.name '${{ github.event.commits[0].author.name }}'
        git config --global user.email '${{ github.event.commits[0].author.email }}'
        git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"
    - name: Commit changes
      run: |
        git add yarn.lock .yarn/cache
        git commit -m "[dependabot skip] autofix yarn cache" # [dependabot skip] is required so that dependabot will fix conflicts automatically
        git push
