name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          targets=${@-"darwin/amd64 darwin/386 linux/amd64 linux/386 windows/amd64 windows/386"}
          for target in $targets; do
            os="$(echo $target | cut -d '/' -f1)"
            arch="$(echo $target | cut -d '/' -f2)"

            echo "----> Building project for: $target"
            GOOS=$os GOARCH=$arch CGO_ENABLED=0 go build ./...
          done
      - name: Test
        run: go test -v ./...
