name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          mkdir -p output
          export GOOS=darwin  && export GOARCH=amd64 && go build -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=darwin  && export GOARCH=arm64 && go build -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=linux   && export GOARCH=386   && go build -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=linux   && export GOARCH=amd64 && go build -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=linux   && export GOARCH=arm   && go build -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=linux   && export GOARCH=arm64 && go build -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=windows && export GOARCH=386   && go build -o ./output/snyk-lsp.$GOOS.$GOARCH.exe
          export GOOS=windows && export GOARCH=amd64 && go build -o ./output/snyk-lsp.$GOOS.$GOARCH.exe
          export GOOS=windows && export GOARCH=arm   && go build -o ./output/snyk-lsp.$GOOS.$GOARCH.exe
          export GOOS=windows && export GOARCH=arm64 && go build -o ./output/snyk-lsp.$GOOS.$GOARCH.exe
          chmod +x output/*

      - name: Test
        env:
          DEEPROXY_API_URL: ${{secrets.DEEPROXY_API_URL}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN }}
        run: |
          echo "Downloading CLI..."
          mkdir -p ./tmp
          curl https://static.snyk.io/cli/latest/snyk-linux > snyk
          chmod +x snyk
          export PATH=$PATH:$PWD
          go test -v ./...

      - name: Static Analysis
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: snyk-lsp-binaries
          path: output/*
          if-no-files-found: error