name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64  go build ./...
          GOOS=darwin GOARCH=arm64  go build ./...
          GOOS=linux GOARCH=386     go build ./...
          GOOS=linux GOARCH=amd64   go build ./...
          GOOS=linux GOARCH=arm     go build ./...
          GOOS=linux GOARCH=arm64   go build ./...
          GOOS=windows GOARCH=386   go build ./...
          GOOS=windows GOARCH=amd64 go build ./...
          GOOS=windows GOARCH=arm   go build ./...
          GOOS=windows GOARCH=arm64 go build ./...
      - name: Test
        env:
          DEEPROXY_API_URL: ${{secrets.DEEPROXY_API_URL}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN }}
        run: |
          echo "Downloading CLI..."
          mkdir -p ./tmp
          curl -sSL https://static.snyk.io/cli/latest/snyk-linux > ./tmp/snyk
          chmod +x ./tmp/snyk
          export PATH=$PATH:./tmp
          go test -v ./...
